version: '3'

services: 
  mysql_test:
    image: mysql
    container_name: mysql_test
    ports: 
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=jinwoo
    volumes:
      - /home/asmanager/task_agile/setup/1.init-database.sql:/home/init.sql
    command: mysql -pjinwoo < /home/init.sql
